services:
  backend:
    build:
      context: .
      args:
        HTTP_PROXY: http://host.docker.internal:10808
        HTTPS_PROXY: http://host.docker.internal:10808
    environment:
      HTTP_PROXY: http://host.docker.internal:10808
      HTTPS_PROXY: http://host.docker.internal:10808
      NO_PROXY: localhost,127.0.0.1
      DATA_DIR: /app/K线data
      CACHE_DIR: /app/cache
    ports:
      - "8000:8000"
    volumes:
      - ./K线data:/app/K线data
      - ./cache:/app/cache
      - ./回测结果.db:/app/回测结果.db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
