# Generated by Django 5.2.4 on 2025-07-05 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                (
                    "symbol",
                    models.CharField(
                        default="ETHUSDT", max_length=20, verbose_name="交易对"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=8,
                        default=1000,
                        max_digits=20,
                        verbose_name="初始资金",
                    ),
                ),
                ("leverage", models.IntegerField(default=125, verbose_name="杠杆倍数")),
                (
                    "bid_spread",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.002,
                        max_digits=10,
                        verbose_name="买单价差",
                    ),
                ),
                (
                    "ask_spread",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.002,
                        max_digits=10,
                        verbose_name="卖单价差",
                    ),
                ),
                (
                    "position_size_ratio",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.02,
                        max_digits=10,
                        verbose_name="仓位比例",
                    ),
                ),
                (
                    "max_position_value_ratio",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.8,
                        max_digits=10,
                        verbose_name="最大仓位比例",
                    ),
                ),
                (
                    "config_json",
                    models.TextField(blank=True, verbose_name="完整配置JSON"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "回测配置",
                "verbose_name_plural": "回测配置",
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="总收益率",
                    ),
                ),
                (
                    "final_equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="最终权益",
                    ),
                ),
                (
                    "total_trades",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="总交易次数"
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="胜率",
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="最大回撤",
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="夏普比率",
                    ),
                ),
                (
                    "result_json",
                    models.TextField(blank=True, verbose_name="详细结果JSON"),
                ),
                (
                    "trades_json",
                    models.TextField(blank=True, verbose_name="交易记录JSON"),
                ),
                (
                    "equity_curve_json",
                    models.TextField(blank=True, verbose_name="权益曲线JSON"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backtest.backtestconfig",
                        verbose_name="回测配置",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "回测结果",
                "verbose_name_plural": "回测结果",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.BigIntegerField(verbose_name="时间戳")),
                ("action", models.CharField(max_length=50, verbose_name="交易动作")),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "买入"), ("sell", "卖出")],
                        max_length=10,
                        verbose_name="方向",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="数量"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="价格"
                    ),
                ),
                ("leverage", models.IntegerField(verbose_name="杠杆")),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="手续费"
                    ),
                ),
                (
                    "long_position",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        max_digits=20,
                        verbose_name="多头仓位",
                    ),
                ),
                (
                    "short_position",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        max_digits=20,
                        verbose_name="空头仓位",
                    ),
                ),
                (
                    "net_position",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        max_digits=20,
                        verbose_name="净仓位",
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="权益"
                    ),
                ),
                (
                    "backtest_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backtest.backtestresult",
                        verbose_name="回测结果",
                    ),
                ),
            ],
            options={
                "verbose_name": "交易记录",
                "verbose_name_plural": "交易记录",
                "ordering": ["timestamp"],
            },
        ),
    ]
